name: AOSP Build

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install git
      run : |
             wget https://raw.githubusercontent.com/igroman787/mytonctrl/master/scripts/install.sh
             sudo bash install.sh -m lite
